variable "sgname" {}
variable "cidr" {}
variable "mytag" {}
variable "amiid" {}
variable "machinetype" {}
variable "keyname" {}
variable "device_name" {}
variable "volume" {}
variable "ebs_size" {}
variable "ebs_type" {}
